### ISSUE TITLE
missing bundle.js?

### ISSUE THREAD

**Issue by Chaoticoz** [Mazelos/Express-React-Boilerplate#1]
The project loads up an empty page.

From index.html: 
`  <script src="/bundle.js"></script>
`

Is this file missing? or is this supposed to point at index,js?

EDIT: I am very new to web dev, so i might just be doing something wrong.

**Comment by Mazelos** [comment]
I , sorry i didn't provide any description so far , you have to run `npm run dev` and Webpack will automatically create bundle.js, or `npm build` to bundle the files without running the server.

**Comment by Chaoticoz** [comment]
Works perfectly! thank you so much! I am starting to get into web dev, and this helps a lot.

**Comment by Mazelos** [comment]
I'm very happy to hear that , thank you!
